name: Prettier Check

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    prettier:
        if: ${{ github.event.action != 'synchronize' }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Prettify code
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: --write **/*.{js,jsx,ts,tsx,json,css,html,yml} --ignore-path .prettierignore --config .prettierrc
